/*global $*/
$.__bodymovin.shapeTypes = {
	shape: 'sh',
    rect: 'rc',
    ellipse: 'el',
    star: 'sr',
    fill: 'fl',
    gfill: 'gf',
    gStroke: 'gs',
    stroke: 'st',
    merge: 'mm',
    trim: 'tm',
    twist: 'tw',
    group: 'gr',
    repeater: 'rp',
    roundedCorners: 'rd',
    offsetPath: 'op',
    puckerAndBloat: 'pb',
    zigZag: 'zz',
}